import type { Analysis } from '../core/model';
import type { VulnInfo } from '../analyzers/repo/enrich';
import { LAYER_COLORS, LAYER_LABELS } from '../analyzers/repo/catalog';
import { compact, formatNumber, hashString, mulberry32 } from './util';

export function download(filename: string, data: Blob | string, type = 'application/octet-stream') {
  const blob = typeof data === 'string' ? new Blob([data], { type }) : data;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function fileStem(a: Analysis) {
  return (a.context.repo?.fullName ?? a.target).replace(/^https?:\/\//, '').replace(/[^\w.-]+/g, '-').replace(/-+$/, '');
}

export function exportJson(a: Analysis) {
  download(`${fileStem(a)}.stackscope.json`, JSON.stringify(a, null, 2), 'application/json');
}

export function titleOf(a: Analysis) {
  return a.context.repo?.fullName ?? a.context.url?.finalUrl.replace(/^https?:\/\//, '').replace(/\/$/, '') ?? a.target;
}

export function toMarkdown(a: Analysis, link: string): string {
  const c = a.summary.counts;
  const h = a.summary.health;
  const lines: string[] = [];
  lines.push(`# ${titleOf(a)} — Stackscope report`, '');
  if (a.context.repo?.description) lines.push(`> ${a.context.repo.description}`, '');
  lines.push(`**Health ${h.score}/100 (${h.grade})** · generated ${new Date(a.createdAt).toUTCString()} · [open interactive map](${link})`, '');
  lines.push('## Stack', '', a.summary.stack.map((s) => `\`${s}\``).join(' · ') || '_none detected_', '');
  lines.push('## Key numbers', '', '| Metric | Value |', '|---|---|');
  for (const [k, v] of Object.entries(c)) lines.push(`| ${k} | ${formatNumber(v)} |`);
  lines.push('', '## Health breakdown', '', '| Factor | Score | Detail |', '|---|---|---|');
  for (const f of h.factors) lines.push(`| ${f.label} | ${f.score} | ${f.detail} |`);
  let archHeader = false;
  for (const layer of Object.keys(LAYER_LABELS) as (keyof typeof LAYER_LABELS)[]) {
    const items = a.nodes.filter((n) => n.layer === layer && ['framework', 'service', 'datastore', 'infra', 'thirdParty'].includes(n.kind));
    if (!items.length) continue;
    if (!archHeader) {
      lines.push('', '## Architecture');
      archHeader = true;
    }
    lines.push('', `### ${LAYER_LABELS[layer]}`, '');
    for (const n of items) lines.push(`- **${n.label}**${n.meta.category ? ` — ${n.meta.category}` : ''} _(${n.confidence})_`);
  }
  const endpoints = a.nodes.filter((n) => n.kind === 'endpoint' && n.meta.method !== 'PAGE');
  if (endpoints.length) {
    lines.push('', `## Endpoints (${endpoints.length})`, '', '| Method | Path | Source |', '|---|---|---|');
    for (const e of endpoints.slice(0, 400)) lines.push(`| ${e.meta.method} | \`${e.meta.path}\` | ${e.meta.file ? `\`${e.meta.file}${e.meta.line ? `:${e.meta.line}` : ''}\`` : ''} |`);
    if (endpoints.length > 400) lines.push(`| … | ${endpoints.length - 400} more | |`);
  }
  const vulnerable = a.nodes.filter((n) => n.kind === 'dependency' && ((n.meta.vulns as VulnInfo[]) ?? []).length);
  if (vulnerable.length) {
    lines.push('', '## Vulnerable dependencies', '', '| Package | Declared | Advisories | Fixed in |', '|---|---|---|---|');
    for (const d of vulnerable) {
      const v = d.meta.vulns as VulnInfo[];
      lines.push(`| ${d.label} | ${d.meta.spec} | ${v.map((x) => `${x.id} (${x.severity})`).join(', ')} | ${v.map((x) => x.fixed).filter(Boolean).pop() ?? '—'} |`);
    }
  }
  if (a.warnings.length) lines.push('', '## Notes', '', ...a.warnings.map((w) => `- ${w}`));
  lines.push('', '---', '_Generated by [Stackscope](' + link + '). Static detection only: dynamic routes and runtime behaviour may be missed._', '');
  return lines.join('\n');
}

export async function exportViewPng(el: HTMLElement, name: string) {
  const { toPng } = await import('html-to-image');
  const bg = getComputedStyle(document.documentElement).getPropertyValue('--bg').trim() || '#070b16';
  const url = await toPng(el, { backgroundColor: bg, pixelRatio: 2, cacheBust: true, filter: (n) => !(n instanceof HTMLElement && n.dataset.noExport !== undefined) });
  const res = await fetch(url);
  download(`${name}.png`, await res.blob());
}

/** 1200×630 social card: title, numbers, health ring and a constellation of the codebase. */
export async function renderShareCard(a: Analysis, url: string): Promise<HTMLCanvasElement> {
  await document.fonts?.ready;
  const W = 1200;
  const H = 630;
  const canvas = document.createElement('canvas');
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d')!;
  const bg = ctx.createLinearGradient(0, 0, W, H);
  bg.addColorStop(0, '#070b16');
  bg.addColorStop(1, '#0c1530');
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);
  ctx.fillStyle = 'rgba(148,163,184,0.10)';
  for (let x = 11; x < W; x += 22) for (let y = 11; y < H; y += 22) ctx.fillRect(x, y, 1.4, 1.4);
  const glow = ctx.createRadialGradient(900, 300, 10, 900, 300, 420);
  glow.addColorStop(0, 'rgba(34,230,255,0.16)');
  glow.addColorStop(1, 'rgba(34,230,255,0)');
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, W, H);

  // constellation: files clustered by module, coloured by layer
  const rand = mulberry32(hashString(a.target));
  const pts = a.nodes.filter((n) => n.kind === 'file' || n.kind === 'thirdParty' || n.kind === 'endpoint').slice(0, 900);
  const modules = [...new Set(pts.map((p) => String(p.meta.module ?? p.kind)))];
  const centers = new Map(modules.map((m, i) => {
    const ang = i * 2.39996;
    const r = 26 * Math.sqrt(i + 1);
    return [m, [900 + Math.cos(ang) * r, 315 + Math.sin(ang) * r * 0.85]];
  }));
  ctx.globalCompositeOperation = 'lighter';
  for (const p of pts) {
    const [cx, cy] = centers.get(String(p.meta.module ?? p.kind))!;
    const ang = rand() * Math.PI * 2;
    const r = Math.sqrt(rand()) * 34;
    const x = cx + Math.cos(ang) * r;
    const y = cy + Math.sin(ang) * r;
    const color = LAYER_COLORS[p.layer ?? 'service'];
    const size = 1 + Math.min(3, Math.sqrt(Number(p.meta.loc ?? 40)) / 10);
    ctx.fillStyle = color + '33';
    ctx.beginPath();
    ctx.arc(x, y, size * 3, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.arc(x, y, size, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.globalCompositeOperation = 'source-over';

  // health ring
  const h = a.summary.health;
  const ringColor = h.score >= 90 ? '#3ee08f' : h.score >= 75 ? '#b4ff39' : h.score >= 60 ? '#ffb547' : '#ff5c7a';
  ctx.lineWidth = 14;
  ctx.strokeStyle = 'rgba(148,163,184,0.18)';
  ctx.beginPath();
  ctx.arc(900, 315, 118, 0, Math.PI * 2);
  ctx.stroke();
  ctx.strokeStyle = ringColor;
  ctx.shadowColor = ringColor;
  ctx.shadowBlur = 24;
  ctx.lineCap = 'round';
  ctx.beginPath();
  ctx.arc(900, 315, 118, -Math.PI / 2, -Math.PI / 2 + (Math.PI * 2 * h.score) / 100);
  ctx.stroke();
  ctx.shadowBlur = 0;
  ctx.fillStyle = 'rgba(7,11,22,0.75)';
  ctx.beginPath();
  ctx.arc(900, 315, 100, 0, Math.PI * 2);
  ctx.fill();
  ctx.textAlign = 'center';
  ctx.fillStyle = ringColor;
  ctx.font = '700 76px "Space Grotesk", sans-serif';
  ctx.fillText(String(h.score), 900, 335);
  ctx.fillStyle = '#8e9cb5';
  ctx.font = '500 16px "JetBrains Mono", monospace';
  ctx.fillText(`grade ${h.grade}`, 900, 368);

  // text block
  ctx.textAlign = 'left';
  ctx.fillStyle = '#22e6ff';
  ctx.font = '600 22px "JetBrains Mono", monospace';
  ctx.fillText('◉ STACKSCOPE', 64, 86);
  ctx.fillStyle = '#e7eef9';
  let title = titleOf(a);
  ctx.font = '700 56px "Space Grotesk", sans-serif';
  while (ctx.measureText(title).width > 640 && title.length > 8) title = title.slice(0, -2);
  if (title !== titleOf(a)) title += '…';
  ctx.fillText(title, 64, 170);
  const desc = a.context.repo?.description ?? a.context.url?.title ?? '';
  if (desc) {
    ctx.fillStyle = '#8e9cb5';
    ctx.font = '400 24px "Space Grotesk", sans-serif';
    let d = desc;
    while (ctx.measureText(d).width > 640 && d.length > 8) d = d.slice(0, -2);
    ctx.fillText(d === desc ? d : d + '…', 64, 214);
  }

  const c = a.summary.counts;
  const stats: [string, number][] = a.mode === 'repo'
    ? [['files', c.files ?? 0], ['endpoints', c.endpoints ?? 0], ['dependencies', c.dependencies ?? 0], ['modules', c.modules ?? 0]]
    : [['third parties', c.thirdParties ?? 0], ['scripts', c.scripts ?? 0], ['API routes', c.endpoints ?? 0], ['pages', c.pages ?? 0]];
  stats.forEach(([label, value], i) => {
    const x = 64 + i * 160;
    ctx.fillStyle = '#e7eef9';
    ctx.font = '700 48px "Space Grotesk", sans-serif';
    ctx.fillText(compact(value), x, 330);
    ctx.fillStyle = '#56657f';
    ctx.font = '500 18px "JetBrains Mono", monospace';
    ctx.fillText(label, x, 360);
  });

  // stack chips
  let x = 64;
  let y = 430;
  ctx.font = '500 20px "JetBrains Mono", monospace';
  for (const s of a.summary.stack.slice(0, 9)) {
    const w = ctx.measureText(s).width + 28;
    if (x + w > 700) {
      x = 64;
      y += 48;
      if (y > 500) break;
    }
    ctx.strokeStyle = 'rgba(148,163,184,0.3)';
    ctx.lineWidth = 1.5;
    roundRect(ctx, x, y - 26, w, 38, 19);
    ctx.stroke();
    ctx.fillStyle = '#c7d2e3';
    ctx.fillText(s, x + 14, y);
    x += w + 10;
  }
  ctx.fillStyle = '#56657f';
  ctx.font = '400 18px "JetBrains Mono", monospace';
  ctx.fillText(url.replace(/^https?:\/\//, ''), 64, 586);
  return canvas;
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

export function badgeMarkdown(siteUrl: string, repoFullName: string) {
  return `[![Explore on Stackscope](https://img.shields.io/badge/explore%20on-Stackscope-22e6ff?style=flat&labelColor=0a1020)](${siteUrl}/r/${repoFullName})`;
}
